### ISSUE TITLE
Incorrect example in Section 3.2

### ISSUE THREAD

**Issue by mmachulak** [KantaraInitiative/wg-uma#145]
Section 3.2 - Example incorrect:

POST /host/scope_reg_uri/photoz.example.com HTTP/1.1
Content-Type: application/json
Host: as.example.com
Authorization: Bearer 204c69636b6c69

{
  "resource_set_id": "112210f47de98100",
  "scopes": [
      "http://photoz.example.com/dev/actions/view",
      "http://photoz.example.com/dev/actions/all"
  ]
}

Firstly, there should be no /photoz.example.com in the path (error). Also, let's change scope_reg_uri to rs_reg_uri? (or match what is in the example in the UMA Configuration, i.e. rsrc_uri). Furthermore, it would be good to highlight an example where a scope is actually not a URI (this is an option).

**Comment by xmlgrrl** [comment]
Left the non-URI scope matter for #170 (which subsumes #147 as already noted), but otherwise completed this.
