### ISSUE TITLE
Incoherent text in Section 3

### ISSUE THREAD

**Issue by mmachulak** [KantaraInitiative/wg-uma#146]
Currently, the text is as following:

*If the RPT is invalid, or if the RPT is valid but has insufficient authorization data, the resource server registers a requested permission at the authorization server that would suffice for the access attempt, and then responds with an HTTP 403 (Forbidden) response, a permission ticket, and instructions on where to go to obtain a valid RPT and authorization data for it.
If the RPT is valid, and if the authorization data associated with the token is sufficient for allowing access, the resource server responds with an HTTP 2xx (Success) response.*

While (Forbidden) is HTTP defined, the (Success) is not.

**Comment by mmachulak** [comment]
A better option would be something like:

*If the RPT is valid, and if the authorization data associated with the token is sufficient for allowing access, the resource server responds with an HTTP response defined by the resource server for this resource (e.g. HTTP 2xx (Successful) response).*

I'd like to discuss this.

**Comment by xmlgrrl** [comment]
Implemented before UMA telecon 2015-08-27.
