### ISSUE TITLE
Unclear text in Section 2.2

### ISSUE THREAD

**Issue by mmachulak** [KantaraInitiative/wg-uma#147]
The current text is as following:

**scopes**
*REQUIRED. An array of strings, any of which MAY be a URI, indicating the available scopes for this resource set. URIs MUST resolve to scope descriptions as defined in Section 2.1. Published scope descriptions MAY reside anywhere on the web; a resource server is not required to self-host scope descriptions and may wish to point to standardized scope descriptions residing elsewhere. It is the resource server's responsibility to ensure that scope description documents are accessible to authorization servers through GET calls to support any user interface requirements. The resource server and authorization server are presumed to have separately negotiated any required interpretation of scope handling not conveyed through scope descriptions.*

Maybe clarify text - It currently may not read well taking into account that some scopes may not be URIs so therefore these scopes cannot really reside "anywhere on the Web" + further explanation does not apply to "string-type scopes".

**Comment by xmlgrrl** [comment]
Implemented before UMA telecon 2015-08-27.
