### ISSUE TITLE
Invalid example in Section 7

### ISSUE THREAD

**Issue by mmachulak** [KantaraInitiative/wg-uma#148]
Invalid example (should be POST). Currently there is:

*PUT /rs/resource_set HTTP/1.1
Content-Type: application/json
...

{
  "name" : "Steve the puppy!",
  "icon_uri" : "http://www.example.com/icons/flower.png",
  "scopes" : [
    "http://photoz.example.com/dev/scopes/view",
    "http://photoz.example.com/dev/scopes/all"
  ]
}*

**Comment by mmachulak** [comment]
Also, include "uri" in this example.

**Comment by xmlgrrl** [comment]
For reference: This is in RSR Sec 7 (https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html#rfc.section.7) in the description of Create.
