### ISSUE TITLE
PAT vs. an ID token for identifying the resource owner

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#150]
In Core Sec 3.2, it says "The PAT provided in the API request implicitly identifies the resource owner ("subject") to which the permission applies." This is strictly true, but philosophically it could be considered awkward to ask an access token to do the job of identification (as Nat Sakimura has pointed out to me in private communication). In the case where OIDC and not just OAuth is being used over the protection API, the resource owner might be explicitly identifiable. Since the quoted specification sentence is meant to provide nonnormative explanation for how the authorization server can understand the context of the API request, it may be a good idea to delve a little further in some fashion, or at least to point to OIDC for how the resource owner could be properly identified.

**Comment by mmachulak** [comment]
Agreed.

**Comment by xmlgrrl** [comment]
Proposed, discussed, and reviewed in UMA telecon 2015-08-27. We can close this.
