### ISSUE TITLE
RPT Endpoint Overloads Token Endpoint Functionality

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#153]
The RPT endpoint takes in an authenticated request from a client application with well-defined parameters ("ticket") and exports a token. This is identical to the Token Endpoint defined in OAuth 2.0, except that OAuth 2.0 responses contain more information about the token being issued, in this case the RPT, including expiration, scopes, and other pieces of information that the client might find useful and helpful. Furthermore, as an extensible response format, the OAuth 2.0 token endpoint response allows for the issuance of other tokens along side the requested access token, such as refresh tokens and ID tokens in the right circumstances.

Recommended fix: remove the RPT endpoint entirely and redefine it as an OAuth 2.0 extension grant utilizing the token endpoint.

**Comment by xmlgrrl** [comment]
For reference:

- Core Sec 3.4.1 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.4.1) defines the client initially approaching the RPT endpoint.
- Various places in Core also "implicitly import" the ordinary OAuth token endpoint for PAT and AAT issuance purposes, so the UMA authorization server is also serving as an OAuth AS and RS for that function.
- An RPT's format is profilable, but its default and mandatory-to-implement format upon introspection is defined in Core Sec 3.3.2 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.3.2).

**Comment by mrpotes** [comment]
I'm very interested in this suggestion, and have talked around it with Eve, who I know has in turn also discussed with others. My understanding is (and I'm sure @xmlgrrl will correct me, or hopefully provide more detail) that this was a design that was considered before but that there were privacy concerns. I'm all for simplifying in the way described, but we probably need to try and make sure we work out what those concerns were and whether they were well founded before we embark down a route that breaks compatibility with UMA 1.0 in a pretty big way?

**Comment by xmlgrrl** [comment]
Yep, color commentary just now provided under #154. These really are one issue, not two.

**Comment by mrpotes** [comment]
I agree - that was what I was trying to convey on #154 myself - perhaps not well enough :)

**Comment by xmlgrrl** [comment]
Discussion on 2015-08-13: Since it requires major breaking changes and further extensive discussion, this belongs in a V2.0 release.

**Comment by xmlgrrl** [comment]
This was initially implemented in UMA 2.0 Core rev 02, with a series of subsequent related revisions: https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-02.html#seek-authorization
