### ISSUE TITLE
Resource Set Registration has extraneous URL parts

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#155]
The resource set registration definition has an extraneous, unnecessary, and confusing `resource_set` portion to its URL. Since the specification defines only one kind of object at the resource, it makes no sense to specify this text in the URL.

Suggested fix: remove the `resource_set` portion of all URLs in the specification.

**Comment by xmlgrrl** [comment]
For reference: This can be seen in RSR Sec 2.3 (https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html#rfc.section.2.3) and in each subsection thereof (and of course in the worked-example appendix).

**Comment by xmlgrrl** [comment]
As confirmed/discussed/directed by the WG on telecon 2016-08-18, the last three spec commits above let us close this issue.
