### ISSUE TITLE
Discovery document inconsistent with related specifications

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#157]
The discovery document uses `dynamic_client_endpoint` to point to the OAuth Dynamic Client Registration Endpoint, whereas OpenID Connect uses `registration_endpoint`. 

Suggested fix: Adopt the OpenID Connect term of `registration_endpoint`

**Comment by xmlgrrl** [comment]
For reference: This is defined in Core Sec 1.4 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.1.4).

**Comment by xmlgrrl** [comment]
For reference: This is defined in Core Sec 1.4 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.1.4).

**Comment by xmlgrrl** [comment]
This was implemented in UMA 2.0 Core rev 02: https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-02.html#am-endpoints
