### ISSUE TITLE
Unnecessary "version" field in discovery document

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#159]
The discovery document has a `version` field that is set to `1.0` but this is not required for functionality. The use of the `version` field makes it impossible to host multiple versions of the UMA protocol simultaneously, since only one can be served from the discovery endpoint as defined today.

A new version of the spec requiring a new discovery document could easily be hosted at a new `.well-known` location, allowing it to have its own format definition. 

Suggested fix: remove the `version` field and define future incompatible discovery documents in new `.well-known` locations.

For background, the OpenID Connect specification used to have a `version` field until the above issue was pointed out during the specification's development. The final specification has no `version` field and it's anticipated that future incompatible updates will use a new location.

**Comment by xmlgrrl** [comment]
For reference: This appears in Core Sec 1.4 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.1.4).

**Comment by xmlgrrl** [comment]
For background: We originally copied this from OIDC, but didn't successfully track its removal.

**Comment by mmachulak** [comment]
Sounds good. But I am not sure that I understand the below:

"The use of the version field makes it impossible to host multiple versions of the UMA protocol simultaneously, since only one can be served from the discovery endpoint as defined today."

How does it make it impossible to have multiple versions of UMA if their discovery endpoints could be hosted in different well-known locations?

**Comment by jricher** [comment]
The `version` field implies that for future versions you would re-use the `.well-known` location but with a different version number (and likely different document content). If you have different versions hosted at different `.well-known` locations, then you don't need the version number inside the document at all. Either way, it's problematic.

**Comment by mmachulak** [comment]
Justin, this I understand. I did not understand why this would be "impossible" to host multiple versions of the UMA protocol.

**Comment by jricher** [comment]
It's impossible to host multiple versions of the UMA protocol at the same `.well-known` location since you can have only one `version` value in that document.

**Comment by mmachulak** [comment]
Justin, sure that's understood. But the fix, as you suggested, is to *"define future incompatible discovery documents in new .well-known locations."* Removal of `version` is OK but it's presence does not make the fix impossible.

**Comment by jricher** [comment]
Correct, but in light of that fix, it's completely redundant and unnecessary, as stated in the original issue title and description.

**Comment by mmachulak** [comment]
That I completely agree with. I only complained about the use of "impossible" in your statement :-)

**Comment by xmlgrrl** [comment]
The WG confirmed on telecon 2016-08-18 that the spec commit above fixes this issue.
