### ISSUE TITLE
Protocol assumes one resource owner per URL

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#161]
The UMA protocol assumes that each individual user at the resource server has a unique URL, but not every API is designed this way. In fact, many OAuth APIs use the OAuth token itself to provide context for the response from the protected resource. For instance, in OpenID Connect, the UserInfo Endpoint is a shared endpoint among all users at an IdP. The OAuth access token presented to the endpoint provides the server with enough information to determine which user profile to return in the response.

API designers are vanishingly unlikely to change their APIs to accommodate the quirks of a security protocol.

**Comment by gffletch** [comment]
Since the PAT is required when the RS is communicating with the AS and the AS can separate based on the RO defined in the PAT... what am I missing?

**Comment by jricher** [comment]
The first time the client talks to the RS it doesn't have the PAT and the RS is required to send the client to one (and only one) AS. This effectively limits the resource to a single AS, and therefore given the arity in UMA a single resource owner.

**Comment by gffletch** [comment]
I think there is a flow mismatch. If a Client asks for access to a resource URL and that resource URL is not yet protected then yes, the RS has no PAT, but then that resource URL is not yet UMA protected. In order for the resource URL to be UMA protected it must be registered with the AS and that registration flow is the protection API and requires the PAT. Again I'm probably missing something:)

**Comment by jricher** [comment]
Sorry, my mistake in terminology -- the client will never have the PAT, I was talking about the RPT. 

However: My point in the above issue is exactly that the individual URL can only be protected by a single AS. That's still true in your discussion above. It seems that insisting on inline discovery here might be a bad step.

**Comment by gffletch** [comment]
Ahh.. I think I see your point. The RS could register the same URL with multiple Authorization Servers because it knows the PAT, but when a client is requesting that URL without an RPT, there is no way for the RS to know which AS it should send the Client to get authorization.

**Comment by jricher** [comment]
Exactly, and there are a lot of APIs that structure their access this way. I don't know the best way to solve this and still have inline discovery, but I still see it as a bug/limitation of UMA that's not spelled out in the spec.

**Comment by jricher** [comment]
This also touches on #163 as the client could be given public info in a 200 class response.

**Comment by gffletch** [comment]
I agree that many APIs rely on the identification of a user while maintaining the same URL in order to return the appropriate data. 

Maybe what we are really addressing is how to apply/layer UMA unto an existing API. Designing an API to be UMA friendly is not that hard, but layering UMA onto an existing OAuth2 API is more complicated.

**Comment by jricher** [comment]
> Designing an API to be UMA friendly is not that hard, but layering UMA onto an existing OAuth2 API is more complicated. 

Yes, this is exactly at the crux of it: if you start with the API, nearly any HTTP API, it's almost trivial to add OAuth to it. It's not trivial to add UMA to it, even if it's already OAuth protected. Philosophically, I've always felt that UMA should "degrade gracefully" to OAuth in the alice-to-alice case, but I'm not sure what the steps of that grade look like.

**Comment by gffletch** [comment]
Since most (if not all) existing OAuth protected APIs rely on one and only one AS, layering UMA into this model isn't that hard since the RS can just work with a single UMA AS. However, once the RS wants to support multiple UMA Authorization Servers, then the simple layering breaks down.

**Comment by mmachulak** [comment]
George, I am not sure this would entirely solve the problem. In the situation where a client tries to access a resource the RS still is unsure in the context of which user at the AS a permission should be registered.

**Comment by xmlgrrl** [comment]
Discussion on 2015-08-13: The constraint is that the RS must be able, based on the C's access attempt with no token and no other context, to distinguish the AS and RO that match the protected resource set. In practice, this likely means that the URI needs to be unique per resource set. Let's mention this constraint in a few places. E.g., in Core Sec 1.3.1 and Core Sec 2. And we also have to put it into RSR Sec 2 and Sec 2.2.

**Comment by xmlgrrl** [comment]
Proposed, discussed, and reviewed in UMA telecon 2015-08-27. We can close this, presuming Maciej has already implemented amendments made on the call.
