### ISSUE TITLE
Protocol assumes one resource per URL

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#162]
The UMA protocol assumes that there's only one resource per URL, but not all APIs are designed this way. Some use contextual information in the request outside of the URL to determine the kind of request being made. For instance, in OpenID Connect's UserInfo Endpoint, the scopes associated with the access token used to make the request to the endpoint determine which parts of a user's profile are returned. The `email` scope maps to the `email` and `email_verified` claims, etc. While this is a trivial example whose specific details could be hacked around, this type of multi-use endpoint isn't unheard of in more complex scenarios.

API designers are vanishingly unlikely to change their APIs to accommodate the quirks of a security protocol.

**Comment by xmlgrrl** [comment]
Discussion on 2015-08-13: The constraint is that the RS must be able, based on the C's access attempt with no token and no other context, to distinguish the AS and RO that match the protected resource set. In practice, this likely means that the URI needs to be unique per resource set. Let's mention this constraint in a few places. E.g., in Core Sec 1.3.1 and Core Sec 2. And we also have to put it into RSR Sec 2 and Sec 2.2.

**Comment by xmlgrrl** [comment]
The solution for this issue is wrapped up with that for #161, so we can close this one.

**Comment by jricher** [comment]
I would suggest adding the note text from 9495bf966fbb992e26e6f090c0b91eb950d64e7d to §1.3.3. as well.
