### ISSUE TITLE
Difficult to return public information

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#163]
The response of the protected resource is expected to always direct the client to the AS, but some APIs can return public information in a non-error response. UMA states that non-error responses are "out of scope" which will lead to needlessly incompatible methods of handling this.

Suggested fix: specify precisely how to handle this use case, such as a "200" class response with a special header.

**Comment by xmlgrrl** [comment]
For reference: This appears in Core Sec 3.1.1 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.1.1): "It SHOULD respond with the HTTP 403 (Forbidden) status code, providing the authorization server's URI in an "as_uri" property in the header, along with the just-received permission ticket in the body in a JSON-encoded "ticket" property. Responses that use any code other than 403 are undefined by this specification; any common or best practices for returning other status codes will be documented in the [UMA-Impl]."

**Comment by xmlgrrl** [comment]
Discussion on 2015-08-13: Since 200 with a special header was suggested in the issue, the presence of the WWW-Authenticate: UMA header would do the job.

**Comment by xmlgrrl** [comment]
Proposed, discussed, and reviewed in UMA telecon 2015-08-27. We can close this, presuming Maciej has already implemented amendments made on the call.
