### ISSUE TITLE
Ticket is returned as JSON regardless of Client's wishes

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#168]
Since the `ticket` is returned from the protected resource, which can define its own data types and APIs, it should respect the Client's encoding and other headers. A client expecting to get XML back from an XML API is going to be very confused by a JSON response. Since the `ticket` is the only value returned in this case, the use of the JSON object structure is needlessly complex.

Suggested fix: return the ticket as part of the `WWW-Authenticate` header or define content-negotiation behavior for the return value.

**Comment by xmlgrrl** [comment]
For reference: This behavior is defined in Core Sec 3.1.1 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.1.1).

**Comment by mmachulak** [comment]
+1 for header.
-1 for content negotiation

**Comment by mmachulak** [comment]
Although after some further thought, I think that JSON might be better than header. The client would implement UMA differently than the actual business API so I think it's OK to have a business XML API and errors returned in JSON.

Nevertheless, I am still against content negotiation.

**Comment by jricher** [comment]
The JSON structure is completely unnecessary for this specific response, though. The ticket is a single string and it doesn't need the structure, so why confuse things?

**Comment by mmachulak** [comment]
Justin, I don't think that there is any confusion. However, I fully understand your point so we should discuss this with the group. I am mostly of a strong opinion that content-negotiation is not a good solution.

**Comment by jricher** [comment]
If there were no confusion, I would not have filed the issue. :)

**Comment by xmlgrrl** [comment]
As discussed on UMA telecon 2015-08-27, the solution for this will be wrapped into that for #163.
