### ISSUE TITLE
Resource Registration ID inconsistency

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#169]
The identity property of the resource set is returned as `_id` but the examples and URI templates all reference it as `rsid`.

**Comment by xmlgrrl** [comment]
For reference: These appear throughout RSR (https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html).

**Comment by xmlgrrl** [comment]
For background: RSR bakes in a commonly used _id primary key field (see, for example, MongoDB: http://docs.mongodb.org/manual/reference/object-id/), and assigns to it the semantic of "resource set identifier".

**Comment by mmachulak** [comment]
Agreed, this could be clarified although this is very minor. It seems clear where the use of identifier is in the body and where it is in the path.
