### ISSUE TITLE
If the resource server is unsuccessful in registering a permission, how does it respond to the client?

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#176]
Core Sec 3.2 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.2) describes error conditions in case there's a failure to register a requested permission propertly, but the subsections of Core Sec 3.1 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.1) only describe what are effectively success-condition responses to the resource server's intermediate interaction with the authorization server.

Should the resource server return some kind of error to the client if something went wrong in the intermediate interaction?

**Comment by mmachulak** [comment]
Eve, I am of the opinion that there should be an error response to the client with no information of what actually happened between the RS and AS. This should be clarified in https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.1

**Comment by xmlgrrl** [comment]
Proposed, discussed, and reviewed in UMA telecon 2015-08-27. We can close this, presuming Maciej has already implemented amendments made on the call.
