### ISSUE TITLE
Clarify that PUT for updating in RSR means a complete replacement

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#177]
The Update Resource Set Description operation (RSR Sec 2.3: https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html#rfc.section.2.3.3, also referenced in the worked-example appendix) uses a PUT, and the intent was for it to be a complete replacement per our Design Principle 4 about RESTfulness (http://kantarainitiative.org/confluence/display/uma/UMA+Requirements). But it's technically possible for a PUT not to be a complete replacement, and for interoperability's sake in terms of authorization server functionality we should make this clear.

**Comment by mmachulak** [comment]
Agreed, although after "Form of an update request, with an access token in the header:" this is clear that the body request has to contain a body of the full resource set description - see "(body contains JSON resource set description to be updated)"
