### ISSUE TITLE
Clarify request methods in the Resource Set Registration protocol

### ISSUE THREAD

**Issue by mmachulak** [KantaraInitiative/wg-uma#178]
Descriptions of methods should contain information what is sent in the request by the Resource Server and what is returned to the RS by the Authorisation Server. Currently, this is implied (and quite obvious) but not fully defined. For example, the text to be defined here: https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html#rfc.section.2.3.1 could be used in https://docs.kantarainitiative.org/uma/rec-oauth-resource-reg.html#rfc.section.2.3.3 as well.

**Comment by xmlgrrl** [comment]
Proposed, discussed, and reviewed in UMA telecon 2015-08-27. We can close this, presuming Maciej has already made amendments made on the call.
