### ISSUE TITLE
Use OIDC specification style of providing a subsection for every type of response

### ISSUE THREAD

**Issue by mmachulak** [KantaraInitiative/wg-uma#179]
(As an editorial aside, it's been suggested to me that the OIDC specification style of providing a subsection for every type of response, as shown here, would be good to emulate: http://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint )

**Comment by xmlgrrl** [comment]
Per discussion on 2013-08-13, we'll take a look at doing this if there's time in the patch release editing cycle, but if not, we'll drop it back.

**Comment by andihindle** [comment]
The re-org for this issue looks fine to me.
