### ISSUE TITLE
What deliverables should the UMA Legal subgroup provide?

### ISSUE THREAD

**Issue by dazzaji** [KantaraInitiative/wg-uma#180]
> I've written up some materials in prep for and following from the initial UMA-Legal call on these wiki pages:  

* [UMA-Legal: Background and Context:](https://github.com/xmlgrrl/UMA-Specifications/wiki/UMA-Legal:-Background-and-Context)

* [UMA-Legal: Use Cases, Roles and Obligations:](https://github.com/xmlgrrl/UMA-Specifications/wiki/UMA-Legal:-Use-Cases,-Roles-and-Obligations)

**Comment by dazzaji** [comment]
In conversations during the Legal subgroup meetings, some people have suggested including example, sample or "standard" legal wording for ToS and other legal instruments for use with UMA deployments.  Not yet sure what those would say, but it would be a sign of success to get to the point of recommending such terms.  If the subgroup deliverables includes both recommended terms and an approach to audit logs for legal compliance or enforceability, we would have a strong set of deliverables.

**Comment by xmlgrrl** [comment]
This work is under way now. A hub page for the work can be found at http://tinyurl.com/umalegal, and it points to our draft CommonAccord model text. Our open issues on the model text will be recorded here under the label "trust".
