### ISSUE TITLE
Informative References in the UMA Spec

### ISSUE THREAD

**Issue by mmachulak** [KantaraInitiative/wg-uma#184]
Currently, the specification has some informative references, e.g. the UMA Participant Roster:
http://kantarainitiative.org/confluence/display/uma/Participant+Roster

Each entry has a date which is mostly outdated (e.g. Participant Roster points to Dec 2014). Prior to any recommendation publishing we should either: 
(a) remove the dates completely; or
(b) update the dates.

**Comment by xmlgrrl** [comment]
These are now updated to be as generic as possible (just the year, where they change frequently).
