### ISSUE TITLE
Craft Wording of CONTRIBUTING.md and LICENSE.md Files for our Repository

### ISSUE THREAD

**Issue by dazzaji** [KantaraInitiative/wg-uma#188]
Here are starting files that will "hold the space" while wording can be discussed and agreed.  

https://github.com/KantaraInitiative/wg-uma/pull/187 

https://github.com/KantaraInitiative/wg-uma/pull/186 

The sooner we have a LICENSE.md file the better (especially given the sensitivity to ensuring good IP practices).  The LICENSE file is where people using GitHub customarily look to see what, if any, IP terms apply to the content of the project, so we should get some file there now and tweak the wording over time.  

Likewise, as soon as we add a CONTRIBUTING.md file people who contribute issues will get an automatic notice screen pop up with a link to whatever IP or other information we want to put people on notice of.  This file automatically triggers the notice (thanks to the awesomeness of GitHub: https://help.github.com/articles/setting-guidelines-for-repository-contributors).  An example of how the notice will look once we add the file can be seen in this image: 
![contributing-guidelines](https://cloud.githubusercontent.com/assets/2357755/9638557/6b3ac6c2-5175-11e5-8fd3-dd6ad44db9b1.jpg)

**Comment by xmlgrrl** [comment]
I have edited the wording of these files, and also changed README.txt to README.md.

I think a link to the actual IPR policy is acceptable, since that's what we have on our KI wiki home page as well; does anyone disagree?

I now think we can get rid of the README entirely, unless there's some other good use to which we could put it. Thoughts?

**Comment by xmlgrrl** [comment]
Ah, I see, README.md appears at the bottom of the project page. Okay, I think this issue can be closed. If someone has comments on the specific wording at this point, they can open a separate issue.
