### ISSUE TITLE
Expand terminology section

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#191]
The terminology section could stand to be expanded with things like the three different access token definitions (and their acronyms) and endpoints. Suggested text:

 - *autorization API token* **AAT**: an OAuth access token with the scope `uma_authorization`, used by the client at the requesting party token endpoint.
 - *protection API token* **PAT**: an OAuth access token with the scope `uma_protection`, used by the resource server at the resource set registration endpoint, permission registration endpoint, and token introspection endpoint.
 - *requesting party token* **RPT**: an OAuth access token associated with a set of permissions, used by the client to connect to the resource server.
 - *requesting party token endpoint* **RPT Endpoint*: a specialized endpoint at the authorization server that issues the RPT to the client.
 - *resource set registration endpoint*: an endpoint at the authorization server that allows the resource server to register resource sets.
 - *permission registration endpoint*: an endpoint at the authorization server that allows the resource server to request permission tickets.
 - *introspection endpoint*: an endpoint at the authorization server that allows the resource server to query about the status and associated rights of an RPT.

There may be more, but these are all very important to the flow of the protocol and get mentioned throughout. The definitions don't have to be complete in the terminology section, just enough of a differentiating reference to function to help the rest of the text make sense.

**Comment by xmlgrrl** [comment]
Looks good as of UMA telecon 2015-09-10.
