### ISSUE TITLE
Permission tickets aren't always structured

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#197]
In §3.2.2, the text "permission ticket is a short-lived structure" erroneously conveys that permission ticket values themselves need to have internal structure. This repeated a few lines down with notions of including expiry information within the ticket. 

In truth, permissions tickets are like OAuth tokens and authorization codes in that they *might* have structure or they *might* be random references into an internal data structure on the authorization server's side. Our implementation in MITREid Connect uses random values with no structure. 

Suggest removing "structure" and "include in" language from this section, and mention that "Since permission tickets are opaque to clients and protected resources, much like authorization codes and access tokens, the authorization server MAY format them however it chooses, for example by including data within the ticket value itself or by using a secure random string to reference data held on the authorization server."

**Comment by xmlgrrl** [comment]
Good suggestions, thanks. We use the word "handle" in defining it up front; I can probably use that in the first sentence to good effect.
