### ISSUE TITLE
XSLT verb rendering

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#198]
The current XSLT seems to render `spanx type=verb` sections as quoted strings in the HTML. It would be preferable for these to be wrapped in `code` elements or another stylistic structure instead. The same for terms in definition lists.

**Comment by xmlgrrl** [comment]
Actually, we've been very bad and haven't used `spanx type=verb` anywhere. I've made a note to go through and take care of this finally.

**Comment by xmlgrrl** [comment]
This specific formatting issue is now complete. We still have formatting items to do, but they're separate from this issue.
