### ISSUE TITLE
Unclear definition of "authorization server's URI"

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#199]
In §3.3.1, the text states that `as_uri` must contain the "authorization server's URI", but this term is not directly explained. Suggest something like "the URI of the authorization server (which may be used by the client for [ UMA Discovery ])".

**Comment by xmlgrrl** [comment]
Ah yes, there are actually a couple of things we could be clearer about here. Something like:

"...with the URI of the authorization server protecting this resource in an `as_uri` parameter (to aid in the client's discovery of the authorization server's configuration data and endpoints as required), and..."

(We got much more specific about definitions when it came to the `issuer` property in 1.4, inspired by OIDC. The `as_uri` should match that, I think, but we probably don't want to be messing with matching requirements at this point.)

**Comment by xmlgrrl** [comment]
It was suggested to make this unambiguous by making this the "issuer URI"; good idea. Let's do it.
