### ISSUE TITLE
Example response not a valid JPEG

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#200]
The example response in §3.3.3 is not a valid JPEG encoded image. At least, I couldn't get it to display. :)

Suggest replacing the faux-JPEG with JSON.

**Comment by xmlgrrl** [comment]
This is an old, old example! You're the first person who tried it. :-) I think I took a real JPEG and hacked off most of the lines. I'll change it.

**Comment by mmachulak** [comment]
Eve,

I don't agree we should change the example if we don't change other
examples. Currently, in Section 3 we have a clear example showing things
photo-related. Unless we change all examples, we should not touch the one
reported by Justin.

Maciej

On 7 September 2015 at 21:59, Eve Maler <notifications@github.com> wrote:

> This is an old, old example! You're the first person who tried it. :-) I
> think I took a real JPEG and hacked off most of the lines. I'll change it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaraInitiative/wg-uma/issues/200#issuecomment-138368695>
> .
>



-- 
Maciej Machulak
email: maciej.machulak@gmail.com
mobile: +44 7999 606 767 (UK)
mobile: +48 602 45 31 66 (PL)

**Comment by xmlgrrl** [comment]
I don't have a problem making the content of examples "coherent"; I recall an edit at some point in the OIDC process that changed an invalid signature block in an example to a valid one, or something similar, which would fall into the same category. Developers often copy and paste examples as part of their testing. Are you thinking that this example should be graphical in nature because of the photo-related theme?

**Comment by mmachulak** [comment]
Eve, I am thinking of making examples coherent. It does not have to be
photo-related at all! :-)

On 8 September 2015 at 16:12, Eve Maler <notifications@github.com> wrote:

> I don't have a problem making the content of examples "coherent"; I recall
> an edit at some point in the OIDC process that changed an invalid signature
> block in an example to a valid one, or something similar, which would fall
> into the same category. Developers often copy and paste examples as part of
> their testing. Are you thinking that this example should be graphical in
> nature because of the photo-related theme?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaraInitiative/wg-uma/issues/200#issuecomment-138571967>
> .
>



-- 
Maciej Machulak
email: maciej.machulak@gmail.com
mobile: +44 7999 606 767 (UK)
mobile: +48 602 45 31 66 (PL)

**Comment by jricher** [comment]
@mmachulak: Unless I misread, what @xmlgrrl  means by "coherent" refers to a single element, ie "fix the JPEG", and not an overarching view of all examples, ie "change everything out to a brand new API". 

I'm in favor of the kind of within-example coherence that @xmlgrrl mentioned, as this is the kind of coherence that was in the OIDC example. Each individual example should make sense on its own.

I'm not in favor of leaving broken examples (like this one) in place just because they fit better with everything else. I also think it's unnecessary (and somewhat contrived and potentially misleading) to have all examples in a specification try to fit the same use case. Especially since there are already several places that don't fit that "one request sequence" model, like the two alternative examples of returning an error. Showing alternative use cases within the spec's examples is a very good thing.

This example should be fixed. Whether that means the rest of the examples get rewritten as a result is up to the editors, but I would recommend diversity. And I want to be clear that with this bug I am *not* suggesting a complete rewrite of other examples. Not only would that be a lot of work, it would require careful scrutiny of every example again and be susceptible to bugs like this one all over.

**Comment by mmachulak** [comment]
Justin,

I might have misread Eve's email then.

As I said earlier, I think examples should be clear. We can make the API
"JSON-friendly" but other examples should be changed too. I find your
approach a bit confusing.

Cheers,
Maciej

On 8 September 2015 at 16:20, Justin Richer <notifications@github.com>
wrote:

> @mmachulak <https://github.com/mmachulak>: Unless I misread, what @xmlgrrl
> <https://github.com/xmlgrrl> means by "coherent" refers to a single
> element, ie "fix the JPEG", and not an overarching view of all examples, ie
> "change everything out to a brand new API".
>
> I'm in favor of the kind of within-example coherence that @xmlgrrl
> <https://github.com/xmlgrrl> mentioned, as this is the kind of coherence
> that was in the OIDC example. Each individual example should make sense on
> its own.
>
> I'm not in favor of leaving broken examples (like this one) in place just
> because they fit better with everything else. I also think it's unnecessary
> (and somewhat contrived and potentially misleading) to have all examples in
> a specification try to fit the same use case. Especially since there are
> already several places that don't fit that "one request sequence" model,
> like the two alternative examples of returning an error. Showing
> alternative use cases within the spec's examples is a very good thing.
>
> This example should be fixed. Whether that means the rest of the examples
> get rewritten as a result is up to the editors, but I would recommend
> diversity. And I want to be clear that with this bug I am *not*
> suggesting a complete rewrite of other examples. Not only would that be a
> lot of work, it would require careful scrutiny of every example again and
> be susceptible to bugs like this one all over.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaraInitiative/wg-uma/issues/200#issuecomment-138576365>
> .
>



-- 
Maciej Machulak
email: maciej.machulak@gmail.com
mobile: +44 7999 606 767 (UK)
mobile: +48 602 45 31 66 (PL)

**Comment by jricher** [comment]
For what it's worth, the change in e502179 fixes this for me.

**Comment by mmachulak** [comment]
Justin,

This is such a minor thing and I *honestly* hate to argue about this.
However, I do find your proposal confusing. I suggest we either revert it
to a "photo-like" example or change other examples. The *photo-like*
example does not have to have ANY data as the content.

Cheers, Maciej

On 8 September 2015 at 17:12, Justin Richer <notifications@github.com>
wrote:

> For what it's worth, the change in e502179
> <https://github.com/KantaraInitiative/wg-uma/commit/e502179de48da5efc9ce13b7f33a7c8d42158e7b>
> fixes this for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaraInitiative/wg-uma/issues/200#issuecomment-138596257>
> .
>



-- 
Maciej Machulak
email: maciej.machulak@gmail.com
mobile: +44 7999 606 767 (UK)
mobile: +48 602 45 31 66 (PL)

**Comment by jricher** [comment]
I agree that it's incredibly minor and that it doesn't actually matter what is in the example so long as it is internally consistent (ie, the conten-type header matches the content type, etc.) 

So with that in mind how about this for the JSON example:

```json
{
  "subject": "Jane",
  "phi": "200",
  "flash": true,
  "exposure": 25,
}
```

It's photo-related so it fits the narrative you're set on, but it's a text-based protocol (JSON) so it is accurately representable inside the spec.

**Comment by xmlgrrl** [comment]
You guys are gluttons for punishment. :-) If you can confirm values for the example by first thing Wednesday my time, I'll put them in before publishing the spec to the group for final review.

**Comment by mmachulak** [comment]
Eve, I am very happy to have learnt a new word! ;-) With this in mind, I
need to say that I do not regret the discussion with Justin ;) The new
example is fine. Even the exposure is set perfectly!:-)

On 9 September 2015 at 07:01, Eve Maler <notifications@github.com> wrote:

> You guys are gluttons for punishment. :-) If you can confirm values for
> the example by first thing Wednesday my time, I'll put them in before
> publishing the spec to the group for final review.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaraInitiative/wg-uma/issues/200#issuecomment-138784872>
> .
>



-- 
Maciej Machulak
email: maciej.machulak@gmail.com
mobile: +44 7999 606 767 (UK)
mobile: +48 602 45 31 66 (PL)

**Comment by gffletch** [comment]
Here is the EXIF data from this image: https://plus.google.com/+GeorgeFletcher/posts/K3Z555XSfgq

```
Date taken:	07/14/15, 5:27 PM UTC-4
Dimensions:	2000 x 1334
File name	: IMG_4769_6D.jpg
File size:	1.73M
Camera:	Canon EOS 6D
Lens	: Sigma 150mm
Focal Length:	150mm
Exposure:	1/320
F Number:	f/5.6
ISO:	400
Camera make:	Canon
Flash:	Not used
Exposure Bias:	-0.33 EV
```

For the example I'd use Focal Length, Exposure, F Number, and ISO.

**Comment by jricher** [comment]
Fantastic, thank you! Translating that into JSON let's go with this:

```json
{
  "f_number": "f/5.6",
  "exposure": "1/320",
  "focal_length_mm": 150,
  "iso": 400,
  "flash": false
}
```

This is good all around: it's got string, number, and boolean values, and it will likely pass the sniff test of a photographer.

**Comment by mmachulak** [comment]
Awesome!

On 9 September 2015 at 16:34, Justin Richer <notifications@github.com>
wrote:

> Fantastic, thank you! Translating that into JSON let's go with this:
>
> {
>   "f_number": "f/5.6",
>   "exposure": "1/320",
>   "focal_length_mm": 150,
>   "iso": 400,
>   "flash": false
> }
>
> This is good all around: it's got string, number, and boolean values, and
> it will likely pass the sniff test of a photographer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaraInitiative/wg-uma/issues/200#issuecomment-138928615>
> .
>



-- 
Maciej Machulak
email: maciej.machulak@gmail.com
mobile: +44 7999 606 767 (UK)
mobile: +48 602 45 31 66 (PL)

**Comment by xmlgrrl** [comment]
...And it will be cool to have a real photo from George as the inspiration, since a lot of our photo sharing discussion has been driven by him. :-)

**Comment by gffletch** [comment]
Well then.... maybe I should pick a better photo :)

**Comment by xmlgrrl** [comment]
I like that one! But you know I like your work pretty much unreservedly.

**Comment by nynymike** [comment]
I suggest "f/3.1215"

**Comment by jricher** [comment]
@nynymike: no.

**Comment by xmlgrrl** [comment]
Little in-joke there... But hey @nynymike, it's already in the spec. :-)
