### ISSUE TITLE
Introspection response is not JWT

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#202]
In §3.4.2, the text states:

```
Syntax and semantics of token data: As defined below; an opaque string value, resolving to an extended JSON Web Token (JWT) [RFC7519] format on introspection at the authorization server.
```

The introspection response is not an extended JWT, but rather its own independent format that imports JWT's claims and elements. The values are in separate registries. The current text also makes it sound like the token itself has to be a JWT.

On the registry point, UMA should register the `permissions` data structure in the introspection registry once introspection reaches RFC status.

**Comment by xmlgrrl** [comment]
+1

I'll make a separate issue for the additional registration of `permissions`.
