### ISSUE TITLE
How does the client get its AAT?

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#203]
In §3.5, the text states that a precondition is:

```
The client has acquired an AAT.
```

However it says nothing about how the client might be able to get one of these. The assumption in UMA is, generally, that the RqP is able to help the client get the AAT. Until AAT's are burned entirely (see #154), we should at least warn developers that this is necessary.

```
The client has acquired an AAT. The means by which the client acquires an 
AAT are out of scope of this protocol. For example, the token may be issued
out of band, or any valid OAuth process may be used. In the case of an 
interactive OAuth flow, the requesting party will need to be able to authorize 
an OAuth client with the `uma_authorization` scope.
```

**Comment by xmlgrrl** [comment]
+1

Since Sec 1.3.1 and 1.3.2 are important and normative wrt PATs and AATs, I'm thinking it would be good to add a mention of them in the section headers there, and refer to these sections respectively from Sec 2 and 3.5.
