### ISSUE TITLE
Missing space in introduction

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#213]
Copyright notice is missing a space in this line:

```
This document is subject to theKantara IPR Policy
```

Likely due to `Kantara` being the start of a link.

**Comment by xmlgrrl** [comment]
I show this one as fixed (in ff2e00c; it was caused by a typo in the stylesheet) in the linked 2015-09-03 versions of the specs, e.g.:

https://docs.kantarainitiative.org/uma/draft-oauth-resource-reg-v1_0_1-2015-09-03.html

Are you still seeing the space?

**Comment by jricher** [comment]
Looks like this has been fixed in the version linked.
