### ISSUE TITLE
The _id is not returned in the location header

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#218]
rs-reg §2.3 currently says:

```
The {_id} is the authorization server-assigned identifier for the web resource corresponding to the 
resource set as returned in the Location header.
```

The value of `_id` is not returned in the `Location` header but rather in the data object itself. The `Location` header contains the full URL of the resource which includes the `_id` but the resource server is not expected to be able to parse the `_id` value out of the `Location` header on its own. Suggest sentence be re-worded as:

```
The {_id} is the authorization server-assigned identifier for the web resource corresponding to the 
resource set. This value is returned in the _id field of the resource set object and included within the URL
returned in the Location header.
```

**Comment by jricher** [comment]
This mistake also occurs in the text defining the _id field of the JSON response:

```
A string value repeating the {_id} as appearing in the Location header.
```

The justification for its double inclusion is likewise confusing.

**Comment by xmlgrrl** [comment]
Thanks, this is a good catch. A clearer justification would perhaps be: "Its appearance in the body makes it readily available as an object identifier for various resource set management tasks."
