### ISSUE TITLE
Make resource set _id in example non-numeric

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#220]
Even though the syntax is correct showing "12345" as a quoted string, the fact that all examples are numeric might lead some to incorrectly conclude that the ID must be numeric, potentially even erroneously returning it as a JSON number instead of a JSON string.

Suggest changing the example ID to "foo-12345-xy" or something similarly not-a-number.

**Comment by xmlgrrl** [comment]
+1
