### ISSUE TITLE
UMA should register the permissions data structure in the token introspection registry

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#223]
UMA should register its `permissions` data structure in the introspection registry once the token introspection spec reaches RFC status.

We can mention our intent to do this in the spec now. If the token introspection spec gets assigned an RFC number before the UMA specs have been prepared for final Recommendation publication, addition of this registration will count as an editorial change.

**Comment by jricher** [comment]
The registry already exists in IANA as part of the pending RFC process: http://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#token-introspection-response

**Comment by xmlgrrl** [comment]
In UMA ad hoc telecon 2015-09-08 (which had quorum), this was the discussion and conclusion:

"Add the registration of “permissions” in the token introspection registry now, because it already exists."
