### ISSUE TITLE
Simplification of "need_info" response

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#237]
The current response structure for "need_info" has structure that seems unnecessary given the function of the response. Current structure is:

``` json

{
 "error": "need_info",
 "error_details": {
   "authentication_context": {
     "required_acr": ["https://example.com/acrs/LOA3.14159"]
   },
   "requesting_party_claims": {
     "required_claims": [
       {
         "name": "email23423453ou453",
         "friendly_name": "email",
         "claim_type": "urn:oid:0.9.2342.19200300.100.1.3",
         "claim_token_format": 
["http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken"],
         "issuer": ["https://example.com/idp"]
       }
     ],
     "redirect_user": true,
     "ticket": "016f84e8-f9b9-11e0-bd6f-0021cc6004de"
   }
 }
}
```

What's the purpose of the `requesting_party_claims` structure? Removing the indirection yields a cleaner and no less expressive structure:

``` json

{
 "error": "need_info",
 "error_details": {
   "authentication_context": {
     "required_acr": ["https://example.com/acrs/LOA3.14159"]
   },
   "required_claims": [
     {
       "name": "email23423453ou453",
       "friendly_name": "email",
       "claim_type": "urn:oid:0.9.2342.19200300.100.1.3",
       "claim_token_format": 
["http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken"],
       "issuer": ["https://example.com/idp"]
     }
   ],
   "redirect_user": true
 }
}
```

NOTE: Removing `ticket` from the response is covered in #205, since this is a direct HTTP call the client doesn't have to keep any additional state between requests.

**Comment by xmlgrrl** [comment]
Completed the simplification process as of Core 2.0 rev 06: https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-06.html

Eliminated an unnecessary internal level and turned redirect_user from a Boolean into a dynamic declaration of an endponi.
