### ISSUE TITLE
Session Fixation Attack on UMA Claims-Gathering Protocol (UMA 1.0.1 Section 3.6.3)

### ISSUE THREAD

**Issue by jmandel** [KantaraInitiative/wg-uma#239]
## Session Fixation Attack on UMA Claims-Gathering Protocol (UMA [1.0.1](https://docs.kantarainitiative.org/uma/rec-uma-core.html) Section [3.6.3](https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.6.3))

*Note: I thought through this attack and mitigation together with @jricher and @SarahSquire. They also helped with the write-up below!*

The trust elevation protocol specified in UMA 1.0.1 section [3.6](https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.6) is vulnerable to a session fixation attack that allows an attacker requesting party to take advantage of a victim's authorization to access protected resources. Specifically, the interaction with the Authorization Server's claims gathering endpoint is vulnerable to the following attack:

### Precondition

1.  Attacker and victim both use the same (legitimate) UMA client. The client has obtained Authorization Access Tokens for both attacker and victim. Note that attacker and victim do not need to use the same instance or session of the client (but the instances must share the same `client_id`).

### Sequence of the attack

1.  Attacker uses the legitimate, uncompromised client to request a protected resource that she should not be able to see. A permission ticket is issued by the Authorization Server, and conveyed to the client by the Resource Server.
2.  The client attempts to obtain a Requesting Party Token from the Authorization Server's RPT endpoint, but receives a `need_info`  error. The client therefore attempts to redirect the victim's browser to the Authorization Server's claims gathering endpoint. But the attacker prevents this redirection, and instead copies the redirect URL (optionally stripping off the `state` parameter), and passes it to a victim.
3.  After being phished with the URL, victim assists the Authorization Server in completing the claims gathering process, proving her identity and any other required details to the authorization server in order to allow access. Victim notices nothing wrong; it looks like she's supplying claims to help launch a client she knows/trusts. In some tight ecosystem instances, the victim’s claims might be passed to the server automatically through SSO.
4.  When the victim is redirected back to the client, no relevant session is found in the client because no state value is present on the request. So the post-redirect request simply fails. (Alternatively, if an attacker controls the victim's network access, she can prevent all communication between victim and client, so the client doesn't even see a spurious/failed request at all.)
5.  After the right amount of time has elapsed, the attacker simulates the post-claims-gathering response in her client, because every parameter of the post-claims-gathering endpoint (`state`, `authorization_state`, `ticket` ) is known to the attacker.
6.  Attacker gains access to protected resources.

#### Note: `state` parameter
Note from the discussion above that the use of the `state` parameter doesn’t help this, as the victim’s client will simply fail. The attacker needs no additional information from the authorization server to signal the client to take the next step.

### Mitigation   
The core issue is that an attacker can predict the entire post-claims-gathering redirect URL, since the return URL contains no information that binds it to the request or response from the authorization server. Thus, a mitigation is to add unpredictable information to the redirect response that’s required by the authorization server in subsequent steps. Two approaches we've considered are:

#### Add an unpredictable `code` parameter to the post-claims-gathering response  
One way to mitigate the attack is to add a new high-entropy parameter (e.g. `code`) to the redirect response, and then to have this value passed along in the subsequent RPT request. This works, but it breaks the symmetry in the way a client contacts the RPT endpoint. Namely: the first time the client contacts the RPT endpoint it would have no code; and the second time it would have a code. This means more complex client-side logic, and special cases.

#### Rotating permission tickets with each call to the Authorization Server  
An alternative (and, we think, preferable) mitigation is to make the `ticket` parameter itself unpredictable, by updating its value whenever a ticket is submitted to the Authorization Server. This makes each permission ticket a nonce, but linked back (in the Authorization Server's accounting) to the original access request (i.e. the requested resource id and scopes). In this scheme, a client can only present a given ticket one time, and receives a new value to replace with it upon presentation. This works for the claims gathering workflow as well as the re-authentication workflow described in [3.6.1](https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.6.1).

New tickets would be generated by the authorization server and communicated to the client at two points:

* In the JSON response from the RPT endpoint
* In the query parameters on the `claims_callback_uri` after a claims-gathering workflow

Clients would be required to discard their existing tickets upon use and use only the latest ticket value  from the authorization server at each subsequent step.

This fix requires changing the language in 3.2.2, which currently states:

> Permission tickets MUST NOT be single-use; this is in order to allow the client to  interact with the authorization server during the claims-gathering flow, which may require multiple interactions, either direct or through redirection of a requesting party.

The current text effectively makes permission tickets behave as session cookies, used to bind several actions together in a sequence. The new approach would have the tickets act as keys to the next step in the sequence, to be replaced by the AS (and client) each time they’re used.

**Comment by jricher** [comment]
For a note, I've done some preliminary work and not only confirmed the attack in our implementation but also the effectiveness of the second mitigation strategy above.

**Comment by jricher** [comment]
This might have implications on the discussion in #205 as well.

**Comment by xmlgrrl** [comment]
Great work!

Whatever mitigation we apply would also affect the Security Considerations section on redirection threats (https://docs.kantarainitiative.org/uma/rec-uma-core-v1_0_1.html#redirect-threats).

Some questions and comments:

Does the attack rely on two instances of a client that has the same credentials, with the attacker Bob (let's call him RqP(a) for attacker -- and the victim Betty -- let's call her RqP(v) -- using these clients in separate environments? It sounds like RqP(a) would forward a phishing link to RqP(v). Or could RqP(a) pass an actual device, such as a mobile device or laptop, to RqP(v)?

Could a suggested mitigation be to require clients to acquire unique credentials (or only accept clients that can obtain unique credentials)?

In my experience working with those who are planning to deploy UMA systems, tightly coupled/narrow ecosystems are largely about enabling the _proactive_ pushing of claims directly to the RPT endpoint -- cf. identity ecosystems, which heavily use IdP-initiated SSO and statically pre-negotiated attribute exchange. As noted in https://docs.kantarainitiative.org/uma/rec-uma-core-v1_0_1.html#claim-push : "If the client is aware of the authorization server's requirements for claims through an out-of-band relationship, the client MAY push claim tokens in an initial interaction with the RPT endpoint." So it's possible that need_info will be little used in them. However, wherever we do find need_info used in the wild, in whatever breadth of ecosystem, it appears we need to find a solution. IOW, saying "Don't use need_info" doesn't seem like a fair mitigation.

**Comment by jricher** [comment]
To your question and mitigation: not really, a client with the same client_id needs to be merely accessible by both the attacker and the victim for this to work, regardless of its credentials. If you really get down to it, the victim doesn't actually need access to the client at all, they just need to be tricked into going to the claims gathering endpoint. It helps the phishing attack if the victim recognizes the client and thinks nothing is wrong (as in Josh's writeup above). 

The attack works whether it's one instance of the client or not, and will work just fine on the same device (though that's a more obvious attack for the victim and all interactive login and delegation is susceptible to that one in different ways). 

Furthermore, requiring separate credentials won't help as this doesn't address the biggest class of client applications (in the OAuth world at least): hosted web apps. These tend to be multi-user apps by design, accessible from remote browsers. As stated in the writeup, the sessions don't have to align at all, and this is by design of the UMA protocol. Are you suggesting that a web app re-register itself for every user in the system, then? That's not likely to work.

Side note, I also agree that "don't use need_info" is not a good mitigation since requiring claims to be proxied through the client would severely limit UMA's applicability to single-security-domain silos.

**Comment by jmandel** [comment]
Thanks @xmlgrrl. I agree that `need_info` enables a very useful, loosely-coupled claims gathering pattern that will be important especially in wider deployment ecosystems. So the resolution should be to drop AS-driven claims-gathering from the protocol.

As for your question about whether the attack *relies* on having two instances of the client: no. Or at least, it's trivia to produce two client sessions on a single device, so there's little difference. For example, an attacker could always open a new browsing session before handing a physical device to a victim.

I don't know about what you mean by "require clients to obtain unique credentials".

**Comment by xmlgrrl** [comment]
Looks like you guys responded simultaneously. Justin answered my question about credentials; now I'm on firmer ground in understanding that it's not the secret that matters, it's the id (client identity), and that's where ever-popular web apps get especially hard to battle.

(Side note to the side note above, I probably wouldn't make a super-strict equation between need_info and size of ecosystem/number of domains, only because the world -- including some of us in the UMA WG working on trust elevation -- keeps working on ways to do more-dynamic trust establishment, but point taken for now. :-) )

In any case, we've got two mitigation approaches we can chew over for starters (also applying similar thinking to #205), and it seems we can be pretty clear about when mitigation is needed.

**Comment by jricher** [comment]
I've been mulling over the two mitigations above, and I think the first one makes sense if we do something even more radical: collapse the claims gathering endpoint and the authorization endpoint into one. It's something that I've wanted on an architectural level (and it would make UMA a much more OAuth-based protocol with less magic sauce), but I can't see how to clearly separate them from an implementation standpoint. This is especially apparent if you don't assume that the RqP can log in to the AS. Still, something to think about.

The second mitigation, which is what we recommend, leverages the UMA constructs more directly and closes other potential concerns. Additionally, from my limited experience implementing it, it helps make the clients slightly dumber (don't need to "remember" tickets between steps).

**Comment by xmlgrrl** [comment]
The WG is discussing this and putting notes in a set of meeting notes here: https://groups.google.com/forum/#!topic/kantara-initiative-uma-wg/Z47vX6OAUK8

**Comment by IDmachines** [comment]
Not sure this helps but just thinking through, sorry late to discussion, so if you used MFA in the claims gathering I think you address some of these concerns.  I can see in some cases you might like to have resuable (remembered) tickets.  In some of the use cases we did a binding with the authentication token as an alternative to MFA.

**Comment by xmlgrrl** [comment]
Hi Sal-- Unfortunately, no... Our Security Considerations already mention this as a mitigation for a different attack, but for this one, authentication of the RqP is too late a stage.

Eve Maler (sent from my iPad) | cell +1 425 345 6756

**Comment by IDmachines** [comment]
k, thanks Eve

**Comment by jricher** [comment]
The attack actually depends on the phished RqP being successfully authenticated by the claims gathering endpoint, through whatever means necessary. The attacker doesn't steal the credentials of the victim in this attack, so MFA doesn't help.

**Comment by IDmachines** [comment]
Thanks Justin, just kicking this around, I was thinking of the equivalent of invoking something you have that might not be available but yet required at authentication time (like HoK).  I understand this may be too many laps into the swim lanes to do anything.  Easiest for me when I am actually building or testing and I don't have the equivalent up here so I appreciate the feedback on the loose musings.  Best, Sal

**Comment by xmlgrrl** [comment]
With the publication of the [UMA Claims-Gathering Extension for Enhanced Security](https://docs.kantarainitiative.org/uma/draft-uma-claims-sec-ext-v1_0.html) specification and its companion [background document](http://kantarainitiative.org/confluence/display/uma/Understanding+the+Session+Fixation+Attack+on+UMA+Claims-Gathering+and+the+Provided+Mitigation), this technical issue is now closed.
