### ISSUE TITLE
enjcthnitn

### ISSUE THREAD

**Issue by nynymike** [KantaraInitiative/wg-uma#243]

**Comment by mmachulak** [comment]
+1

On Fri, 29 Jan 2016 19:12 Mike Schwartz <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KantaraInitiative/wg-uma/issues/243>.
>
-- 

Maciej Machulak (sent from mobile)

**Comment by xmlgrrl** [comment]
Huh?

**Comment by xmlgrrl** [comment]
Okay, fun's over. :-) I'm going to close this issue as having been a mistake...
