### ISSUE TITLE
Add 'description' to scope document

### ISSUE THREAD

**Issue by nynymike** [KantaraInitiative/wg-uma#271]
In Section 2.1.1, Scope Descriptions, it would be nice if there was a 'description' key. Something like

```
description  OPTIONAL  A human-understandable explanation of what granting the scope means.

```

**Comment by xmlgrrl** [comment]
Added this for consideration in V2.0 as a "semi-easy issue".

**Comment by xmlgrrl** [comment]
From [UMA telecon 2017-03-02](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-03-02) (see notes for internal links): First of all, we need some security considerations around sanitizing all such text (including the existing human-readable text fields), to ensure there's no active scripting in there. We don't currently have that; we only have it for the icon URIs. What does sanitizing mean? It seems ill-defined in the case of natural-language text being displayed.
AI: Eve: Insert language about "sanitizing", pointing to a non-normative example of such action, such as this (from George); Jin points to this as the vuln.
Next challenge: Resource description documents have an RO context, and the RS is basically responsible for doing any L10N before the human-readable strings get to the AS; not our problem for I18N. But the human-readable strings involved in a scope description do have this problem. Do we want to suggest the OIDC-style "hash trick"? We discussed this in the email around #269. Justin likes the normative language in RFC 7591 better. George suggests making this being a "developer-readable" mechanism only.
We agree that it's the right pattern to have both the name and the description fields for both. We prefer the dynamic client registration definition of the I18N/L10N mechanism, and will point to its mechanism by reference for both the resource and scope name and description fields. 7591 already covers the circumstance of "any human-facing fields", so we don't have to add that.
