### ISSUE TITLE
Scope string: "friendly name" and "identifier" the same: do they need to be split?

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#276]
In the ad hoc discussion post-[UMA telecon 2017-01-19](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-01-19), we had a discussion that I don't think I captured in the notes: While the "name" property for a scope description defines itself ([Sec 2.1.1](https://docs.kantarainitiative.org/uma/ed/oauth-resource-reg-2.0-04.html#action-desc) in RReg 2.0 rev 04) as being a human-readable string, that leaves it without a separate (if desired) machine-readable scope string. In implementations it's been treated primarily as the latter and displayed also as the former, so effectively serving as both.

In the case of resources, these two concepts are naturally split because the AS gives back an identifier.

**Comment by nynymike** [comment]
yes, personally I think "displayName" would be more clear for the human readable version.

**Comment by xmlgrrl** [comment]
From [UMA telecon 2017-03-02](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-03-02): We can close this issue.
