### ISSUE TITLE
Clients, credentials, client types, and security considerations

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#278]
Right now in UMA 2.0 Core rev 12 [Sec 1.4.2](https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-12.html#authorization-api), all we really have left about client credentials is this:

"A client seeking access to a protected resource needs OAuth client credentials issued by the authorization server protecting that resource."

But really that would be a [confidential client](https://tools.ietf.org/html/rfc6749#section-2.3) we'd be talking about. At this point this is more of a garden-variety OAuth client. Should we offer special cautions in the Security Considerations about certain kinds of clients, or is that all covered already (by OAuth and our own sections)?

**Comment by jricher** [comment]
I'd say this is covered by OAuth. The client's credentials include its `client_id`, which is required even for public clients.

**Comment by xmlgrrl** [comment]
I've removed the text and it'll be gone in rev 14 for our consideration. Unless someone wants to get fancy and say something about, say, types of clients (confidential/public) in the context of our particular grant -- in which case please propose specific wording -- let's plan to close this by Feb 9.
