### ISSUE TITLE
Check/fix all examples for missing required (and optional) fields; other editorial

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#293]
For example:

- Core rev 20 [Sec 3.6.4](https://docs.kantarainitiative.org/uma/wg/uma-core-2.0-20.html#rfc.section.3.6.4): Ticket missing in redirect example
- Core rev 20 [Sec 3.6.2](https://docs.kantarainitiative.org/uma/wg/uma-core-2.0-20.html#rfc.section.3.6.2): Example needs grant type
- Core rev 20 [Sec 3.6.2](https://docs.kantarainitiative.org/uma/wg/uma-core-2.0-20.html#rfc.section.3.6.2): This section mentions SAML, but the example is about OIDC. The text should either mention OIDC instead, or add a mention of OIDC.

Thanks to Prabath S for these comments!

**Comment by xguttner** [comment]
Core rev 20 [Sec 1.4.2](https://docs.kantarainitiative.org/uma/wg/uma-core-2.0-20.html#rfc.section.1.4.2): I believe it should be **claims interaction endpoint** in the sentence: "For this to happen, the client needs the authorization server to have statically declared a claims redirection endpoint in its configuration document."

**Comment by xmlgrrl** [comment]
Ah, thank you, you are correct, good "thinko" catch. The AS can only declare a claims _interaction_ endpoint.

**Comment by xmlgrrl** [comment]
It turns out that the [Sec 3.6.2](file:///Users/eve/Documents/wg-uma-formatted/uma-core-2.0-xx.html#claim-push) conversion not yet done (mentioned in the commit above) is not quite as trivial/editorial as you might think. The spec text for `claim_tokens` still assumes JSON structure form, but since there isn't an example for it, it's unclear what exactly to do.

Discussing this in an email thread with @jricher et al., I posed the question of whether we should be keeping the JSON structure and form-urlencoding it, or going form-urlencoded native. I wondered if the former would be easier since the current JSON structure is nested. Justin, thinking this looked pretty messy (with which I agree), backed up from this a bit and asked why we really need the nested structure instead of going with the common and perhaps 100% case of supplying a single claim token, which would allow flattening. Indeed, can't think of any case where ID tokens or SAML assertions etc. are used where you actually use more than one at a time.

So if there's only ever one claim token, with its (single) claim token format, the example showing pushed claims would look something like this (with line breaks for display purposes only):

```
grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Auma-ticket
&ticket=016f84e8-f9b9-11e0-bd6f-0021cc6004de
&claim_token_format=http%3A%2F%2Fopenid.net%2Fspecs%2Fopenid-connect-core-1_0.html%23IDToken
&claim_token=eyj0...
```

Any problem with this approach?
