### ISSUE TITLE
Do we need the UMA error invalid_request?

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#304]
Or have we thought of all the UMA errors we need? This would only be needed for the protection API, as the UMA ticket grant is now pretty much using all OAuth errors or need_info or request_submitted. See Core rev 20 [Sec 4](https://docs.kantarainitiative.org/uma/wg/uma-core-2.0-20.html#uma-error-response).

**Comment by jricher** [comment]
Doesn't look like we need this one, especially because it's already defined in https://tools.ietf.org/html/rfc6749#section-4.1.2.1

**Comment by xmlgrrl** [comment]
Yeah, we'd only potentially need it for FedAuthz now. And we've got other error responses for that:

- [Sec 3.2](https://docs.kantarainitiative.org/uma/ed/oauth-uma-federated-authz-2.0-02.html#reg-api) for resource registration: `unsupported_method_type` and `not_found`
- [Sec 4.3](https://docs.kantarainitiative.org/uma/ed/oauth-uma-federated-authz-2.0-02.html#rfc.section.4.3) for permission requests: `invalid_resource_id` and `invalid_scope`
- Whatever [RFC 7662](https://www.rfc-editor.org/rfc/rfc7662.txt) defines

**Comment by xmlgrrl** [comment]
A call for comment after putting out Grant and FedAuthz revs 03 produced none, and there was no further comment on [UMA telecon 2017-05-12](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-05-12), so let's close this one without further action.
