### ISSUE TITLE
Is error_details structure level valuable, or better to promote its innards?

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#308]
We've had the `error_details` structure as part of the `need_info` response for a long time (most recently Grant rev 02 [Sec 3.3.6](https://docs.kantarainitiative.org/uma/ed/oauth-uma-grant-2.0-02.html#authorization-failure). We've simplified that structure a bit over time. Is the `error_details` level itself superfluous? It's supposed to contain at least one of `required_claims` or `redirect_user`, or both. Is it better just to have `need_info` go straight to that level?

Note that such a change would also impact a mention in [Sec 7.4.1](https://docs.kantarainitiative.org/uma/ed/oauth-uma-grant-2.0-02.html#rfc.section.7.4.1) as well.

**Comment by xmlgrrl** [comment]
To be specific, the worked example in that section would go from this:

```
HTTP/1.1 403 Forbidden
Content-Type: application/json
Cache-Control: no-store
...

{  
   "error":"need_info",
   "ticket":"ZXJyb3JfZGV0YWlscw==",
   "error_details":{  
      "required_claims":[  
         {  
            "name":"email23423453ou453",
            "friendly_name":"email",
            "claim_type":"urn:oid:0.9.2342.19200300.100.1.3",
            "claim_token_format":[  
               "http://openid.net/specs/openid-connect-core-1_0.html#IDToken"
            ],
            "issuer":[  
               "https://example.com/idp"
            ]
         }
      ],
      "redirect_user":"https://as.example.com/rqp_claims?id=2346576421"
   }
}
```

To looking like this (where `required_claims` and `redirect_user` get promoted to be at the same level as `error` and `ticket`):

```
HTTP/1.1 403 Forbidden
Content-Type: application/json
Cache-Control: no-store
...

{  
   "error":"need_info",
   "ticket":"ZXJyb3JfZGV0YWlscw==",
    "required_claims":[  
       {  
          "name":"email23423453ou453",
          "friendly_name":"email",
          "claim_type":"urn:oid:0.9.2342.19200300.100.1.3",
          "claim_token_format":[  
             "http://openid.net/specs/openid-connect-core-1_0.html#IDToken"
          ],
          "issuer":[  
             "https://example.com/idp"
          ]
       }
    ],
    "redirect_user":"https://as.example.com/rqp_claims?id=2346576421"
}
```

**Comment by mrpotes** [comment]
This might be nice to do, but not really necessary.

**Comment by xmlgrrl** [comment]
In [UMA telecon 2017-05-12](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-05-12), we decided to recommend doing this. To be implemented in rev 04 for consideration.

**Comment by xmlgrrl** [comment]
Per [UMA telecon 2017-05-18](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-05-18): The recommendations from the previous week, as implemented in rev 04, are acceptable.
