### ISSUE TITLE
Does the PAT need an actual standardized scope name?

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#309]
I'm trying to think of a reason to standardize `uma_protection` now that FedAuthz is its own spec now. Rhetorically, I do find it's valuable to have the access token labeled a "PAT" because we talk about resource owner context in various places, but what would happen if we didn't mandate the scope name for it? Could we just mandate that the protection API has to be OAuth-protected and give the resulting AT a name?

**Comment by jricher** [comment]
We _could_ do that -- but then we'd have an interop problem as the client (which is the RS) wouldn't know what scope to ask for when talking to the RS (which is the protection API of the AS) that it hasn't met before. In other words, you'd move that necessary step to a manual documentation and out of band component.

Better to have the API definition, which we control, also define the OAuth protection semantics.

**Comment by xmlgrrl** [comment]
Ah, you're right, my apologies. We considered interop explicitly in issue #108 in January, and decided to close with no action already. So `uma_protection` stays.
