### ISSUE TITLE
Challenges relying on client scope pre-registration in authorization assessment

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#310]
Grant [Sec 3.3.1](https://docs.kantarainitiative.org/uma/ed/oauth-uma-grant-2.0-02.html#uma-grant-type) and [Sec 3.3.4](https://docs.kantarainitiative.org/uma/ed/oauth-uma-grant-2.0-02.html#authorization-assessment):

Mike S suggests that requiring client pre-registration of scopes (in order to allow scope requests to count) is problematic for loose coupling; if you check an API documentation page, statically register for credentials for your client app, and (somehow) pre-register for scopes as part of that process, at some much later date your app may reasonably want to request a scope at the token endpoint that was added later. It seems impractical to demand that the AS provide, and the client dev keep up, a manual process for pre-registering all scopes.

I would add that, in the static pre-registration/request use case (which is still the common case vs. dynamic), there's no way to make our MUST in Sec 3.3.1 truly testable. We could perhaps change it to a SHOULD...

We're already more "normative" with our set math than [6749 Sec 3.3](https://tools.ietf.org/html/rfc6749#section-3.3), for good reason. But if the MUST in Sec 3.3.1 changed to a SHOULD or were dropped altogether, the intersection portion of our _RequestedScopes_ = _PermissionTicket_ ∪ (_ClientRequested_ ∩ _ClientRegistered_) calculation in Sec 3.3.4 perhaps goes a bit too far, and it should just be _RequestedScopes_ = _PermissionTicket_ ∪ _ClientRequested_.

**Comment by jricher** [comment]
I'm in favor of keeping it as-is as a MUST. It's extremely common practice in OAuth implementations to limit clients to request only the scopes that they're registered for. In cases where client needs change over time, the registration for the client needs to change over time to accommodate that. This isn't an undue burden -- this is in fact an essential security pressure for the client developer to keep things up to date. Changing the scopes being asked for is essentially the client changing its capabilities, and such capabilities ought to be reflected at the AS.

Bear in mind that the RS can *still* request scopes outside of the client's registration set in its ticket request, and that's still good functionality which isn't up for debate here.

And in cases where clients aren't registering for or requesting scopes? The rest of the system still works in a dumb-in-a-different-way UMA 1.0 fashion.

**Comment by xmlgrrl** [comment]
In [UMA telecon 2017-05-12](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-05-12), we noted there seems to be consensus all the way around on this. To be implemented in rev 04 for consideration.

**Comment by xmlgrrl** [comment]
Per [UMA telecon 2017-05-18](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-05-18): Keeping the current language -- requiring no changes to rev 04 -- is acceptable. To be closed without action.
