### ISSUE TITLE
Isn't the implicit grant threat a generic and well-understood OAuth threat?

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#311]
FedAuth [Sec 7.1](https://docs.kantarainitiative.org/uma/ed/oauth-uma-federated-authz-2.0-02.html#rfc.section.7.1):

If so, do we need to say it, vs. individual communities of interest profiling what to do for themselves? In OAuth and UMA security profiles that I'm aware of, they're already constraining things like "don't using anything but the authorization code flow" and "don't use anything but confidential clients", etc.

(This is currently the only FedAuthz-unique security consideration.)

**Comment by nynymike** [comment]
I was thinking of the RqP client being a browser based client. Do you want to return a PCT to this kind of client? Are there any restrictions or considerations on returning an RPT?

**Comment by jricher** [comment]
@nynymike: There's no implicit grant for RPTs -- there's only the ticket grant. For a browser based client to do UMA 2.0, it's akin to using the authz code flow inside a browser, which is doable (if you allow CORS on your token endpoint, and maybe a couple other things). I do not believe that it's a good idea to develop an implicit-style grant analogue.

**Comment by jricher** [comment]
To the actual issue raised (on PATs): We should probably just say that PATs are OAuth access tokens and are susceptible to all of the things that those are. It's not a bad thing to have a bunch of warnings about the stuff that can go wrong, but is this spec the place to collect that? There are a few good resources already, including a possible future "best practices" document for browser clients from the IETF, that we can point to. I vote to inherit by reference the considerations in RFC's 6749, 6750, 6819, and any others. UMA is not special in this regard, and that's a good thing indeed.

**Comment by xmlgrrl** [comment]
@jricher, yeah, I'd really rather do all this by reference. OAuth-protecting the protection API is a totally vanilla choice by now, further highlighted by the spec refactoring.

**Comment by nynymike** [comment]
Would it make sense to specify that browser based clients are not supported? It seems like every other developer I talk to these days is using some Javascript client-side framework.

**Comment by jricher** [comment]
Why would we say it's not supported? If they can do the grant, then it's supported. They are going to have the same kinds of requirements for storing tokens and the like as a server side client. 

The difference is that we're not optimizing for browser-based clients like the implicit flow tried to do.

**Comment by xmlgrrl** [comment]
In [UMA telecon 2017-05-12](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-05-12), there was agreement to remove, and to say instead "The PAT is an OAuth token and, as such, is susceptible to OAuth threats." To be implemented in rev 04 for consideration.

**Comment by xmlgrrl** [comment]
Per [UMA telecon 2017-05-18](http://kantarainitiative.org/confluence/display/uma/UMA+telecon+2017-05-18): The recommendations from the previous week, as implemented in rev 04, are acceptable.
