### ISSUE TITLE
Permission endpoint request implies array cannot be used for single resource identifier

### ISSUE THREAD

**Issue by mrpotes** [KantaraInitiative/wg-uma#339]
Section 4.1 states that:
> The body of the HTTP request message contains a JSON object (for a request containing a single resource identifier) or array of objects (for a request containing more than one resource identifier)

The statement of `for a request containing more than one resource identifier` for an array seems to restrict the resource server to _having_ to use the object form if it only has one resource identifier, but switch to the array form _only_ when it has more than one. This seems overly complicated for the resource server, and it would seem reasonable to instead say `for a request containing one or more resource identifiers` for the array, allowing the RS to choose what payload structure it sends.

**Comment by xmlgrrl** [comment]
For completeness's sake, noting that UMA telecon [2017-08-07](https://groups.google.com/forum/#!topic/kantara-initiative-uma-wg/JP303iN2_pY) decided this issue.
