### ISSUE TITLE
Token error response should defer to 6749

### ISSUE THREAD

**Issue by mrpotes** [KantaraInitiative/wg-uma#343]
Section 3.3.6 should state that the error codes and conditions listed there are in addition to those defined in RFC6749. For example, `invalid_client` is still a valid error code for when the client does not exist.

**Comment by ciseng** [comment]
+1

**Comment by xmlgrrl** [comment]
That seems like a very good "hygiene" suggestion. These are listed in [6749 Sec 5.2](https://tools.ietf.org/html/rfc6749#section-5.2).

**Comment by xmlgrrl** [comment]
For completeness's sake, note that decision was made in UMA telecon [2017-08-08](https://groups.google.com/forum/#!topic/kantara-initiative-uma-wg/YLS0wIDqRz0).
