### ISSUE TITLE
Require AS to convey RS's descriptions of scopes and resource sets accurately to RO

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#86]
From UMA telecon 2013-12-12-: There's nothing in any technical spec that forces accurate AS display of RS-registered scope/resource set metadata, in order to make it technically testable. So we have two choices: 1) Design a way for the RS to sign or otherwise cryptographically secure the stuff it's registering so that when the AS displays it, there's some sort of "trustmarking" you can do, or 2) Think about putting something in the Binding Obs as a stopgap to force the AS to promise to the RS that it won't misrepresent the scope names, icons, etc.

We'd like to explore the latter for now.

**Comment by xmlgrrl** [comment]
In UMA ad hoc telecon 2015-09-08 (which had quorum), this was the discussion and conclusion:

"We would love to be able to force the AS to faithfully represent elements registered by the RS that are intended for the RO’s user interface. Let’s continue to leave this for the “BL” level, not the “T” level, of specification. No action in the RSR spec for now.

Domenico notes that in Italy, the parties are required to sign something. This is truly at the “agreement” level. This may relate to Adrian’s intentions around his new issue #224, and similar follow-on opportunities. There were cases in Italian civil law that relate to this requirement.

(We won’t deep-dive into this for now, but #224 is about Accounting for Disclosures, which is similar to Sal’s idea of an “exception notice”. It’s not for a V1.0.1 timeframe, but we’re warm to the idea! And it relates to consent receipts nicely.)"

Close with no action.

**Comment by aleclaws** [comment]
This feature is possible with the Manage API at the RS. The RO can read the resources/scopes directly from the RS, and could therefore compare to what is being presented by the AS

(Not looking to reopen, maybe https://github.com/KantaraInitiative/wg-uma/issues/224 is a better spot to continue this?)
