### ISSUE TITLE
A "start_at" capability for permission validity periods

### ISSUE THREAD

**Issue by xmlgrrl** [KantaraInitiative/wg-uma#94]
As suggested by Zhanna and others in email on 2014-07-21:

- I was wondering if  it makes sense to  have an optional “start_at” property in the context of http://docs.kantarainitiative.org/uma/draft-uma-core.html#rfc.section.3.3.2. This property would be used  to set permission’s start time in-the-future.  If start_at is set to the current time it becomes equivalent to issued_at time.

- If we add it, should the value of a start_at parameter be optional, defaulting to the current time, or required, to eliminate clock skew weirdness and variability in the spec? I would make it optional, defaulting to the current time (=issued_at), with the value  not greater than expire_at time. Also, (in case if this does not introduce significant perf overhead) should  issued_at property be the "required” one since It’s value is important to lessen the potential ambiguity of the RPT.

- The JWT spec provides expiry (exp), issued at (iat) and not before (nbf), all three of which are optional.

- Where possible and sensible, I think there is value is being consistent with the JWT spec - it will allow for considerable simpler implementation for use-cases that cross specifications (for example, where claims pass across UMA, OICD and XACML (JSON) realms), in that it will limit conversions (and resultant error risks).

It's a useful and well-understood model.

**Comment by tsitkov** [comment]
This one was included into the latest core version under the "nbf", right?

**Comment by xmlgrrl** [comment]
Yes, this is covered by the token introspection object/JWT model that we follow with "nbf".
